### PR TITLE
Improve gem structure

### PR DESCRIPTION
**Pull request by luislavena**
Hello,

I took the liberty and made some changes to the structure used by this gem adding some conventions used in other gems with C extensions:
- ext, lib, and test folder structure
- Rely on rake-compiler for compilation
- Upgrade to latest conventions of RubyGems, Rake and test task
- Use a simple `Gemfile` to bootstrap local development

While I'm not fond to Bundler usage, last point might help others that want to work on this library.

This structure helps set the foundation for better cross-compilation support too.

Hope you accept this and thank you for taking the time and maintain this library!

:heart: :heart: :heart:

### CODE REVIEW

**Comment by abscondment** [comment]
Please merge this! Ruby 2.0 can't build the extension without a proper ext directory structure.

See rubygems/rubygems#411 and arika/ruby-termios#1 for more info.

**Comment by bbozo** [comment]
@luislavena, you might as well fork the repo and continue there, mtodd doesn't seem to be around

**Comment by luislavena** [comment]
@bbozo @abscondment all this is in my company's fork area17/geoip-city (forked before the rename)

**Comment by findchris** [comment]
@mtodd Are you still maintaining this gem?

**Comment by luislavena** [comment]
@findchris seems @mtodd is not answering but @alindeman took the lead

@alindeman should I rebase this from your latest changes? without this newer RubyGems cannot be used since is lacking some structure.

Thank you.

**Comment by alindeman** [comment]
> @alindeman should I rebase this from your latest changes? without this newer RubyGems cannot be used since is lacking some structure.

Sounds good! Ping me when it's rebased.

**Comment by luislavena** [comment]
@alindeman ping!

Please find the rebased commits against master.

This branch also downloads the free City db from MaxMind. Perhaps that can be removed when #9 is merged, but until then, this fixes the issues when running some tests (I can remove that if you want)

Please let me know.

/cc @findchris and @mtodd for code review.

Thank you!

:heart: :heart: :heart:

**Comment by findchris** [comment]
Thanks @luislavena 

Haven't had a chance to test locally, but looks good from what I can browse on github.

**Comment by alindeman** [comment]
Nice, I like this.

**Pull request merged**
