### PR TITLE
Respect LDFLAGS and CFLAGS from environment

### PR DESCRIPTION
**Pull request by scottjg**
Need this to build against geoip library that lives in your boxen root

/cc @mastahyeti

### CODE REVIEW

**Comment by btoews** [comment]
:+1: you rock @scottjg

**Comment by alindeman** [comment]
Thanks!

**Comment by alindeman** [comment]
I might have some time this evening to bump the version and push to rubygems. That said, are any of you using the gem for current projects? Additional maintainers would probably be a good thing here. Thoughts @mtodd? :)

**Comment by alindeman** [comment]
0.8.2 pushed to rubygems.org

**Comment by findchris** [comment]
@mtodd and @alindeman Yes, I am using the gem in production still.

**Pull request merged**
