### PR TITLE
Reorganize gem to compile with ruby2

### PR DESCRIPTION
**Pull request by Gazer**
I'v tested with Ruby 1.9.3 and Ruby 2.0.0 and compile and install without problem.

You could also try it adding to a Gemfile : 

<pre>
gem 'geoip-c', require: "geoip", git: "git://github.com/Gazer/geoip.git", branch: "ruby2"
</pre>

### CODE REVIEW

**Comment by findchris** [comment]
:+1:
Status on this?

**Comment by alindeman** [comment]
I've not had trouble compiling on Ruby 2. How can I reproduce a failure on Ruby 2 locally?

**Comment by madis** [comment]
I tried to compile the gem on OS X 10.8.4 for Ruby 2.0.0 for few hours. I narrowed the problem down quite a bit but am not sure of what the solution would be. 

Here are my findings:
Background:
I tried compiling the gem against Maxmind's original C library installed both ways: using homebrew and compiled from source. The results were the same.
1. I successfully compiled the gem for 1.9.3 using gcc
2. Compiling for 2.0.0 failed because `have_func('GeoIP_addr_to_num', 'GeoIP.h')` couldn't find the dependencies
   I extracted the test C programs that _mkmf_ uses to check the dependencies

I created a [gist showing these dependencies and compilation commands used by _have_func_](https://gist.github.com/madis/6634472)

I don't know that much about binary formats produced by different compilers but I have 2 hypotheses about the cause of failure:
1. clang looks for the libraries from different locations
2. the Maxmind's library was compiled using different compiler and the clang compiled version can't be linked against it.

I hope someone can solve this issue and I am willing to help with providing more details or discussing the issue.

**Comment by madis** [comment]
@alindeman could you post which compiler flags were used (gems/geoip-c-0.9.0/mkmf.log) when compiling the gem and under which OS did you do it?

**Comment by alindeman** [comment]
> @alindeman could you post which compiler flags were used (gems/geoip-c-0.9.0/mkmf.log) when compiling the gem and under which OS did you do it?

I use OS X locally. builds with `/usr/bin/cc`. `cc --version` is `Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)`

And Linux on the production machines: builds with `gcc`. `gcc --version` is `gcc (Debian 4.4.5-8) 4.4.5`

**Comment by luislavena** [comment]
@Gazer can you try latest master? I believe this is already sorted out by the changes made by me.

@alindeman I think this is old and before the gem structure that was already merged. I suggest closing it out.

**Comment by alindeman** [comment]
Thanks!

**Pull request closed without merging**
